apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myreact-app
  name: myreact-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreact-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myreact-app
    spec:
      containers:
      - image: gcr.io/project-id/myreact-app
        imagePullPolicy: Always
        name: myreact-app
